extends:
  - standard-with-typescript
  - prettier #Disables all rules that conflict with prettier
rules:
  no-tabs: off
  indent: off
  "@typescript-eslint/indent": off
  "@typescript-eslint/space-before-function-paren": off
  "@typescript-eslint/explicit-function-return-type": off
  "no-return-await": off
  "@typescript-eslint/return-await": off
env:
  jest: true
  node: true
  es2021: true
overrides: []
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: .