branches:
  - name: main
ci: false
debug: true
dryRun: true
npmPublish: false
# repositoryUrl: — no need, will use from git origin
tagFormat: 'v${version}'
plugins:
  - '@semantic-release/commit-analyzer'

# Global plugin options (will be passed to all plugins)
preset: 'conventionalcommits'